language: swift
osx_image: xcode9.0
before_install:
script:
  - xcodebuild clean -scheme Graph | xcpretty
  - xcodebuild -project Graph.xcodeproj -scheme Graph -destination 'name=Generic iOS Device' | xcpretty